package docubot

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/codalotl/codalotl/internal/gocode"
	"github.com/codalotl/codalotl/internal/gocodetesting"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCountMissingDocs_DefaultCountsFixtureTargets(t *testing.T) {
	conv := &responsesCompleter{responses: []string{"unexpected"}}

	withCodeFixture(t, func(pkg *gocode.Package) {
		before := packageFileContents(t, pkg)

		count, err := CountMissingDocs(pkg, AddDocsOptions{
			BaseOptions: BaseOptions{Completer: conv},
		})
		require.NoError(t, err)
		assert.Equal(t, 11, count)

		count, err = CountMissingDocs(pkg, AddDocsOptions{
			DocumentTestFiles: true,
			BaseOptions:       BaseOptions{Completer: conv},
		})
		require.NoError(t, err)
		assert.Equal(t, 13, count)

		assert.Empty(t, conv.convs)
		assert.Equal(t, before, packageFileContents(t, pkg))
	})
}

func TestCountMissingDocs_OnlyDocumentExportedIdentifiers(t *testing.T) {
	files := map[string]string{
		"code.go": dedent(`
			// Package mypkg exercises public documentation counting.
			package mypkg

			// DocumentedPublic already has docs.
			func DocumentedPublic() {}

			func Public() {}
			func private() {}

			// PublicType has type docs.
			type PublicType struct {
				Public string
				private string
			}

			type privateType struct {
				Public string
			}

			var PublicValue, privateValue = 1, 2
		`),
		"generated.go": dedent(`
			// Code generated by x; DO NOT EDIT.
			package mypkg

			func Generated() {}
		`),
	}

	gocodetesting.WithMultiCode(t, files, func(pkg *gocode.Package) {
		count, err := CountMissingDocs(pkg, AddDocsOptions{
			OnlyDocumentExportedIdentifiers: true,
		})

		require.NoError(t, err)
		assert.Equal(t, 3, count)
	})
}

func TestCountMissingDocs_DocumentTestFilesIncludesBlackBoxPackage(t *testing.T) {
	files := map[string]string{
		"code.go": dedent(`
			// Package mypkg exercises test documentation counting.
			package mypkg
		`),
		"whitebox_test.go": dedent(`
			package mypkg

			import "testing"

			func TestWhitebox(t *testing.T) {}

			func ExportedSamePackageHelper() {}
			func unexportedSamePackageHelper() {}
		`),
		"blackbox_test.go": dedent(`
			package mypkg_test

			import "testing"

			func TestBlackbox(t *testing.T) {}

			func ExportedBlackBoxHelper() {}
			func unexportedBlackBoxHelper() {}
		`),
	}

	gocodetesting.WithMultiCode(t, files, func(pkg *gocode.Package) {
		count, err := CountMissingDocs(pkg, AddDocsOptions{
			DocumentTestFiles:               true,
			OnlyDocumentExportedIdentifiers: true,
		})

		require.NoError(t, err)
		assert.Equal(t, 2, count)
	})
}

func TestCountMissingDocs_OnlyDocumentImportantIdentifiers(t *testing.T) {
	code := dedent(`
		func Public() {}

		type privateType struct {
			field string
		}

		func (privateType) helper() {}

		func small() {}
	`) + "\n" + bigFunctionSource("big")

	gocodetesting.WithCode(t, code, func(pkg *gocode.Package) {
		count, err := CountMissingDocs(pkg, AddDocsOptions{
			OnlyDocumentImportantIdentifiers: true,
		})
		require.NoError(t, err)
		assert.Equal(t, 5, count)

		count, err = CountMissingDocs(pkg, AddDocsOptions{
			OnlyDocumentImportantIdentifiers: true,
			ExcludeIdentifiers:               []string{"privateType"},
		})
		require.NoError(t, err)
		assert.Equal(t, 3, count)
	})
}

func TestCountMissingDocs_ImportantAndExportedOnlyAreMutuallyExclusive(t *testing.T) {
	gocodetesting.WithCode(t, "func Foo() {}", func(pkg *gocode.Package) {
		count, err := CountMissingDocs(pkg, AddDocsOptions{
			OnlyDocumentExportedIdentifiers:  true,
			OnlyDocumentImportantIdentifiers: true,
		})

		require.Error(t, err)
		assert.ErrorContains(t, err, "mutually exclusive")
		assert.Zero(t, count)
	})
}

func TestNeedsDocs_DefaultAndExportedModes(t *testing.T) {
	files := map[string]string{
		"code.go": dedent(`
			// Package mypkg has docs.
			package mypkg

			// Public has docs.
			func Public() {}

			func private() {}
		`),
	}

	gocodetesting.WithMultiCode(t, files, func(pkg *gocode.Package) {
		needsDocs, err := NeedsDocs(pkg, AddDocsOptions{})
		require.NoError(t, err)
		assert.True(t, needsDocs)

		needsDocs, err = NeedsDocs(pkg, AddDocsOptions{
			OnlyDocumentExportedIdentifiers: true,
		})
		require.NoError(t, err)
		assert.False(t, needsDocs)
	})
}

func TestNeedsDocs_ImportantAndExportedOnlyAreMutuallyExclusive(t *testing.T) {
	gocodetesting.WithCode(t, "func Foo() {}", func(pkg *gocode.Package) {
		needsDocs, err := NeedsDocs(pkg, AddDocsOptions{
			OnlyDocumentExportedIdentifiers:  true,
			OnlyDocumentImportantIdentifiers: true,
		})

		require.Error(t, err)
		assert.ErrorContains(t, err, "mutually exclusive")
		assert.False(t, needsDocs)
	})
}

func packageFileContents(t *testing.T, pkg *gocode.Package) map[string]string {
	t.Helper()

	contents := make(map[string]string)
	addFiles := func(prefix string, p *gocode.Package) {
		for name := range p.Files {
			body, err := os.ReadFile(filepath.Join(p.AbsolutePath(), name))
			require.NoError(t, err)
			contents[prefix+name] = string(body)
		}
	}
	addFiles("main/", pkg)
	if pkg.TestPackage != nil {
		addFiles("test/", pkg.TestPackage)
	}
	return contents
}
