package gocode

import (
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestParse verifies that Parse can read a file.
func TestParse(t *testing.T) {
	// Create a temporary file with a simple Go program
	tempDir := t.TempDir()
	tempFile := filepath.Join(tempDir, "test.go")

	// Original content without comment
	original := "package testpkg\n\nfunc TestFunc() {}\n"
	err := os.WriteFile(tempFile, []byte(original), 0644)
	require.NoError(t, err)

	// Create a File
	goFile := &File{
		FileName:         "test.go",
		RelativeFileName: "test.go",
		AbsolutePath:     tempFile,
		Contents:         []byte(original),
		PackageName:      "testpkg",
		IsTest:           false,
	}

	// Parse the file
	fset := token.NewFileSet()
	_, err = goFile.Parse(fset)
	require.NoError(t, err)

	// Verify AST was populated
	assert.NotNil(t, goFile.AST)
	assert.Equal(t, goFile.FileSet, fset)
}

func TestPersistContents(t *testing.T) {
	// Create a temporary file with a simple Go program
	tempDir := t.TempDir()
	tempFile := filepath.Join(tempDir, "test.go")

	// Original content
	original := "package testpkg\n\nfunc Foo() {}\n"
	err := os.WriteFile(tempFile, []byte(original), 0644)
	require.NoError(t, err)

	// Create a File
	goFile := &File{
		FileName:         "test.go",
		RelativeFileName: "test.go",
		AbsolutePath:     tempFile,
		Contents:         []byte(original),
		PackageName:      "testpkg",
		IsTest:           false,
	}

	// Modify the contents
	newContent := "package testpkg\n\nfunc Bar() {}\n"
	goFile.Contents = []byte(newContent)

	// Persist the modified contents
	err = goFile.PersistContents(false)
	require.NoError(t, err)

	// Verify the file was written to disk with the new content
	diskContents, err := os.ReadFile(tempFile)
	require.NoError(t, err)
	assert.Equal(t, newContent, string(diskContents))

	// Clone and persist using PersistNewContents:
	clone := goFile.Clone()
	newestContent := "package testpkg\n\nfunc Qux() {}\n"
	err = clone.PersistNewContents([]byte(newestContent), true)
	require.NoError(t, err)

	assert.Equal(t, newestContent, string(clone.Contents))
	assert.Equal(t, newContent, string(goFile.Contents)) // original didn't change

	// Disk changed:
	diskContents, err = os.ReadFile(tempFile)
	require.NoError(t, err)
	assert.Equal(t, newestContent, string(diskContents))

	// it was reparsed:
	assert.NotEqual(t, goFile.FileSet, clone.FileSet)
	assert.NotEqual(t, goFile.AST, clone.AST)
}

func TestFileIsCodeGenerated(t *testing.T) {
	f := &File{Contents: []byte("// Code generated by x; DO NOT EDIT.\npackage foo\n")}
	assert.True(t, f.IsCodeGenerated())

	f = &File{Contents: []byte("package foo\n")}
	assert.False(t, f.IsCodeGenerated())
}
