package gemini

import "net/http"

// Backend identifies a Gemini backend.
type Backend string

// Backend constants select the Gemini backend implementation.
const (
	BackendUnspecified Backend = ""           // BackendUnspecified makes NewClient use its default backend.
	BackendGeminiAPI   Backend = "gemini-api" // BackendGeminiAPI selects the public Gemini API backend.
)

// HTTPOptions configures Gemini request URL composition and headers.
type HTTPOptions struct {
	// BaseURL is the unversioned API root used to build Gemini REST endpoints. Pass values such as https://host or https://host/custom-prefix, not https://host/v1beta.
	// This package appends /v1beta/... itself.
	BaseURL string

	// Headers are merged into outgoing requests. Per-request headers override client-level headers with the same key.
	Headers http.Header
}

// GenerateContentConfig configures GenerateContentStream requests.
type GenerateContentConfig struct {
	HTTPOptions       *HTTPOptions    // HTTPOptions supplies per-request URL and header overrides.
	SystemInstruction *Content        // SystemInstruction is the optional system-level instruction.
	Temperature       *float32        // Temperature controls sampling randomness when set.
	CandidateCount    int32           // CandidateCount requests the number of response candidates.
	MaxOutputTokens   int32           // MaxOutputTokens limits generated output tokens.
	StopSequences     []string        // StopSequences stop generation when any sequence is produced.
	Tools             []*Tool         // Tools are function tools made available to the model.
	ToolConfig        *ToolConfig     // ToolConfig controls how the model may use tools.
	ThinkingConfig    *ThinkingConfig // ThinkingConfig configures Gemini thinking options.
}

// Content represents one message sent to or returned from Gemini.
type Content struct {
	Parts []*Part `json:"parts,omitempty"` // Parts are the ordered content parts for the message.
	Role  string  `json:"role,omitempty"`  // Role identifies the message author, such as "user" or "model".
}

// Role identifies the author of a Content value.
type Role string

// Role constants identify supported Gemini content authors.
const (
	RoleUser  Role = "user"  // RoleUser marks content provided by the user.
	RoleModel Role = "model" // RoleModel marks content generated by the model.
)

// Part represents one supported Gemini content part.
type Part struct {
	Text             string            `json:"text,omitempty"`             // Text is the text content for this part.
	Thought          bool              `json:"thought,omitempty"`          // Thought reports whether this part contains model thought content.
	ThoughtSignature []byte            `json:"thoughtSignature,omitempty"` // ThoughtSignature is opaque Gemini state associated with thought content.
	FunctionCall     *FunctionCall     `json:"functionCall,omitempty"`     // FunctionCall is a tool invocation requested by the model.
	FunctionResponse *FunctionResponse `json:"functionResponse,omitempty"` // FunctionResponse is a tool result returned to the model.
}

// FunctionCall represents a model-requested function invocation.
type FunctionCall struct {
	ID   string         `json:"id,omitempty"`   // ID identifies this function call when Gemini provides one.
	Name string         `json:"name,omitempty"` // Name is the function name to invoke.
	Args map[string]any `json:"args,omitempty"` // Args are the JSON object arguments for the function call.
}

// FunctionResponse is the supported subset of Gemini function responses.
//
// Only ID, Name, and Response are preserved. Fields exposed by google.golang.org/genai such as Scheduling, WillContinue, Parts, and other unsupported fields are
// discarded during unmarshal.
type FunctionResponse struct {
	ID       string         `json:"id,omitempty"`       // ID identifies the function call being answered when Gemini provided one.
	Name     string         `json:"name,omitempty"`     // Name is the function name being answered.
	Response map[string]any `json:"response,omitempty"` // Response is the JSON object result returned by the function.
}

// Tool describes functions the model may call.
type Tool struct {
	FunctionDeclarations []*FunctionDeclaration `json:"functionDeclarations,omitempty"` // FunctionDeclarations are the functions available through this tool.
}

// FunctionDeclaration describes a function the model may call.
type FunctionDeclaration struct {
	Description          string `json:"description,omitempty"`          // Description explains what the function does and when to use it.
	Name                 string `json:"name,omitempty"`                 // Name is the function name exposed to the model.
	ParametersJsonSchema any    `json:"parametersJsonSchema,omitempty"` // ParametersJsonSchema is the JSON Schema for the function arguments.
}

// ToolConfig configures how the model may use tools.
type ToolConfig struct {
	FunctionCallingConfig *FunctionCallingConfig `json:"functionCallingConfig,omitempty"` // FunctionCallingConfig controls function-call behavior.
}

// FunctionCallingConfig constrains model function calling.
type FunctionCallingConfig struct {
	AllowedFunctionNames []string                  `json:"allowedFunctionNames,omitempty"` // AllowedFunctionNames restricts calls to these function names when set.
	Mode                 FunctionCallingConfigMode `json:"mode,omitempty"`                 // Mode selects how the model may use functions.
}

// FunctionCallingConfigMode selects how the model may use declared functions.
type FunctionCallingConfigMode string

// Function calling mode constants define supported Gemini function-call policies.
const (
	FunctionCallingConfigModeAuto FunctionCallingConfigMode = "AUTO" // FunctionCallingConfigModeAuto lets the model choose between text and function calls.
	FunctionCallingConfigModeAny  FunctionCallingConfigMode = "ANY"  // FunctionCallingConfigModeAny requires the model to produce a function call.
	FunctionCallingConfigModeNone FunctionCallingConfigMode = "NONE" // FunctionCallingConfigModeNone disables function calls.
)

// ThinkingConfig is passed through to generationConfig.thinkingConfig.
//
// ThinkingLevel is serialized as-is. IncludeThoughts only requests thoughts; this client surfaces Thought and ThoughtSignature only when the API returns them. The
// client does not aggregate or reconstruct thought text or thought signatures across stream events.
type ThinkingConfig struct {
	IncludeThoughts bool          `json:"includeThoughts,omitempty"` // IncludeThoughts asks Gemini to include thought parts when supported.
	ThinkingBudget  *int32        `json:"thinkingBudget,omitempty"`  // ThinkingBudget is the optional token budget for thinking.
	ThinkingLevel   ThinkingLevel `json:"thinkingLevel,omitempty"`   // ThinkingLevel selects the requested thinking effort level.
}

// ThinkingLevel selects the requested Gemini thinking effort level.
type ThinkingLevel string

// Thinking level constants define supported Gemini thinking effort levels.
const (
	ThinkingLevelMinimal ThinkingLevel = "MINIMAL" // ThinkingLevelMinimal requests minimal thinking effort.
	ThinkingLevelLow     ThinkingLevel = "LOW"     // ThinkingLevelLow requests low thinking effort.
	ThinkingLevelMedium  ThinkingLevel = "MEDIUM"  // ThinkingLevelMedium requests medium thinking effort.
	ThinkingLevelHigh    ThinkingLevel = "HIGH"    // ThinkingLevelHigh requests high thinking effort.
)

// FinishReason identifies why Gemini stopped generating a candidate.
type FinishReason string

// Finish reason constants identify Gemini candidate termination causes.
const (
	FinishReasonStop       FinishReason = "STOP"       // FinishReasonStop indicates the candidate stopped naturally.
	FinishReasonMaxTokens  FinishReason = "MAX_TOKENS" // FinishReasonMaxTokens indicates the candidate reached the maximum token limit.
	FinishReasonSafety     FinishReason = "SAFETY"     // FinishReasonSafety indicates generation stopped for safety reasons.
	FinishReasonRecitation FinishReason = "RECITATION" // FinishReasonRecitation indicates generation stopped because of recitation policy.
	FinishReasonBlocklist  FinishReason = "BLOCKLIST"  // FinishReasonBlocklist indicates generation stopped because of blocked terms.

	// FinishReasonProhibitedContent indicates generation stopped because of prohibited content.
	FinishReasonProhibitedContent FinishReason = "PROHIBITED_CONTENT"

	// FinishReasonSPII indicates generation stopped because of sensitive personally identifiable information.
	FinishReasonSPII FinishReason = "SPII"

	// FinishReasonMalformedFunctionCall indicates the model produced an invalid function call.
	FinishReasonMalformedFunctionCall FinishReason = "MALFORMED_FUNCTION_CALL"

	FinishReasonUnexpectedToolCall FinishReason = "UNEXPECTED_TOOL_CALL" // FinishReasonUnexpectedToolCall indicates the model produced an unexpected tool call.
	FinishReasonOther              FinishReason = "OTHER"                // FinishReasonOther indicates a stop reason not otherwise represented.
	FinishReasonNoImage            FinishReason = "NO_IMAGE"             // FinishReasonNoImage indicates expected image output was not generated.
	FinishReasonImageSafety        FinishReason = "IMAGE_SAFETY"         // FinishReasonImageSafety indicates image generation stopped for safety reasons.

	// FinishReasonImageProhibitedContent indicates image generation stopped because of prohibited content.
	FinishReasonImageProhibitedContent FinishReason = "IMAGE_PROHIBITED_CONTENT"
)

// GenerateContentResponse is one response event from a Gemini generate-content stream.
type GenerateContentResponse struct {
	// Candidates are the candidate responses in this stream event.
	Candidates []*Candidate `json:"candidates,omitempty"`

	// ModelVersion is the Gemini model version that produced the response.
	ModelVersion string `json:"modelVersion,omitempty"`

	// PromptFeedback describes prompt-level blocking feedback when present.
	PromptFeedback *GenerateContentResponsePromptFeedback `json:"promptFeedback,omitempty"`

	// ResponseID identifies the Gemini response when provided.
	ResponseID string `json:"responseId,omitempty"`

	// UsageMetadata reports token usage when provided.
	UsageMetadata *GenerateContentResponseUsageMetadata `json:"usageMetadata,omitempty"`
}

// Candidate is one model candidate in a generate-content response.
type Candidate struct {
	Content       *Content     `json:"content,omitempty"`       // Content is the candidate content returned by Gemini.
	FinishMessage string       `json:"finishMessage,omitempty"` // FinishMessage explains why generation finished when provided.
	TokenCount    int32        `json:"tokenCount,omitempty"`    // TokenCount is the token count for this candidate when provided.
	FinishReason  FinishReason `json:"finishReason,omitempty"`  // FinishReason identifies why generation stopped for this candidate.
	Index         int32        `json:"index,omitempty"`         // Index is the candidate index in the response.
}

// GenerateContentResponsePromptFeedback describes prompt-level blocking feedback.
type GenerateContentResponsePromptFeedback struct {
	BlockReason        BlockedReason `json:"blockReason,omitempty"`        // BlockReason identifies why the prompt was blocked.
	BlockReasonMessage string        `json:"blockReasonMessage,omitempty"` // BlockReasonMessage explains the block reason when provided.
}

// BlockedReason identifies why Gemini blocked a prompt.
type BlockedReason string

// GenerateContentResponseUsageMetadata reports token usage returned by Gemini.
type GenerateContentResponseUsageMetadata struct {
	CachedContentTokenCount int32 `json:"cachedContentTokenCount,omitempty"` // CachedContentTokenCount is the number of cached content tokens.
	CandidatesTokenCount    int32 `json:"candidatesTokenCount,omitempty"`    // CandidatesTokenCount is the number of generated candidate tokens.
	PromptTokenCount        int32 `json:"promptTokenCount,omitempty"`        // PromptTokenCount is the number of prompt tokens.
	ThoughtsTokenCount      int32 `json:"thoughtsTokenCount,omitempty"`      // ThoughtsTokenCount is the number of thinking tokens.
	ToolUsePromptTokenCount int32 `json:"toolUsePromptTokenCount,omitempty"` // ToolUsePromptTokenCount is the number of tool-use prompt tokens.
	TotalTokenCount         int32 `json:"totalTokenCount,omitempty"`         // TotalTokenCount is the total token count reported by Gemini.
}

// Ptr returns a pointer to v.
func Ptr[T any](v T) *T {
	return &v
}
